services:
  # PHP-APACHE
  www:
    build: docker
    container_name: www_karukera
    ports:
      - "8001:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev
    environment:
      MAILER_DSN: smtp://9d58de415e8c9e:efc1dc4d7b5bb6@sandbox.smtp.mailtrap.io:2525?encryption=tls&auth_mode=login
      ADMIN_EMAIL: "ratianarivoruddy@gmail.com"
      MAILER_FROM_ADDRESS: "ratianarivoruddy@gmail.com"

  db:
    image: mysql
    container_name: mysql_karukera
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmnin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: