services:
   #PHP-APACHE
  www:
    build: docker
    image: karukera-www-staging
    container_name: www_karukera_staging
    #ports:
      #- "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:
     external: true
     name: karukera_dev
